name: deploy

on: [push, repository_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install Nodejs Lib
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Hexo Lib
        run: |
          npm install hexo-cli -g
          npm install 

      - name: Cache to Hexo
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: Generate and Compression
        run: |
          hexo clean
          hexo g
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public